[package]
name = "roicalc"
version = "0.1.0"
edition = "2024"
authors = ["Philip Keil <github@pkeil.de>"]
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
eframe = "0.31.1"
env_logger = "0.11.7"
native-dialog = "0.7.0"
calamine = "0.26.1"